Rbu/rtdb3 config extend
RoboCup-MSL/rtdb2 pull request #4
Opened 2021-03-29 18:31 UTC by RobBurgers

2021-03-29 19:56 UTC, janfeitsma requested changes
Let me know how much you still want to address before merging. I will then merge and update my branch afterwards, so I can get some experience with using the new context builder.

2021-03-29 19:56 UTC, janfeitsma commented on comm/CMakeLists.txt
> +message(STATUS "PO library: ${Boost_PROGRAM_OPTIONS_LIBRARY}")
message can be removed

2021-03-29 19:56 UTC, janfeitsma commented on config/rtdb2_configuration.xml
> +     * compression     (optional)  deprecated
Hm, so it would appear I applied compression at database level instead of comm.
Maybe we should devise a stress-tester. Nice to have.

2021-03-29 19:56 UTC, janfeitsma commented on rtdb2/RtDB2Configuration.h
> +enum RtDB2ProcessType
Better to use enum class, to not freely expose value definitions? That is the pattern I adopted since many years anyway.

2021-03-29 19:56 UTC, janfeitsma commented on test.sh
> -# RTDB now requires this environment variable to be set
Explicitly unset for testing? Or maybe also consider to throw a more explicit error if set. I had some funny failures when the env was still present.

2021-03-29 19:56 UTC, janfeitsma commented on test/config/extensive_configuration_v2.xml
> +  Networks
Maybe we should move the (repeated) documentation from xml to README.md?

2021-03-30 19:18 UTC, RobBurgers commented
I have covered all your comments. I deliberately left the documentation in one test xml.

2021-03-31 15:22 UTC, janfeitsma approved these changes

2021-03-31 15:23 UTC, merged